FROM openjdk:21 as builder
LABEL authors="kpale"


WORKDIR /app/msvc-cursos
COPY ./pom.xml /app
COPY ./msvc-cursos/.mvn ./.mvn
COPY ./msvc-cursos/mvnw .
COPY ./msvc-cursos/pom.xml .
RUN ./mvnw clean package -Dmaven.test.skip -Dmaven.main.skip -Dspring-boot.repackage.skip && rm -r ./target/
#RUN ./mvnw dependecy:go-offline
COPY ./msvc-cursos/src ./src
RUN ./mvnw clean package -DskipTests

FROM openjdk:21 as publish
WORKDIR /app
COPY --from=builder /app/msvc-cursos/target/msvc-cursos-0.0.1-SNAPSHOT.jar .
EXPOSE 8002

ENTRYPOINT ["java", "-jar", "msvc-cursos-0.0.1-SNAPSHOT.jar"]